TanStack/form

src/formInput.js
Sometimes, I'd like `FormInput` to be an inline DOM element (by default, it uses `div` tag, so it's a block element) - I can add CSS targeting `.FormInput` class, but I think allowing users to customize the class name of `FormInput` seems like a more flexible solution.
=> Allow passing custom className to FormInput

README.md
#31 
Noticed this when implementing some radios in a form, thought it might mitigate some questions. Thanks for the great library 👍  Saves me a ton of time.
=> Add missing import on RadioGroup/Radio example

src/form.js
`resetForm` use `this.getInitialState()` which is undefined since this commit: https://github.com/tannerlinsley/react-form/commit/9035b82234b862d96ee4c6550bcba9982e5ef907#diff-62acef2590804164cb77b4b5aced00ebL38
=> Fix resetForm

src/components/form-fields/Checkbox.js, src/components/form-fields/NestedForm.js, src/components/form-fields/Radio.js, src/components/form-fields/RadioGroup.js, src/components/form-fields/Select.js, src/components/form-fields/Text.js, src/components/form-fields/TextArea.js
- All inputs now internally use `onChange` instead of `onInput` as per recommended via React best practices.
- All inputs now consistently use and proxy `onBlur`.
- All inputs now consistently use a hybrid `onChange(newValue, event)` callback, instead of a separate `fieldDidUpdate` and `onChange` prop.
- All inputs now apply `...rest` props so as to not accidentally clobber internal props.
Fixes #132
=> Normalize input fields' callbacks and props

.babelrc, package.json, src/components/ReduxForm.js
This uses the latest class binding syntax for instance-bound methods.  No more rebinding :)
=> Move babel config to .babelrc

dev/Intro.js, src/components/ReduxForm.js
allows retrieving an instance of the api from a parent component, much like using a `ref`. :)
=> Add getApi prop and docs

src/components/FormField.js
I'm writing a custom input which based on `RadioGroup` component, I couldn't get `field` property from props because `field` was destructed from Component props.
https://github.com/react-tools/react-form/blob/5c7c76cda719256f1401d2aa06c75a1174a9b025/src/components/FormField.js#L65
Here's my implementation:
```
const RadioGroup = FormField(({ options, fieldName, disabled }) => {
if (!options || options.length === 0) {
return false
}
return (
<_RadioGroup field={fieldName}>
{group =>
options.map((option, i) => (
<label key={i}>
<Radio
group={group}
className='radio'
value={option.value}
disabled={disabled}
/>
<span>{option.label}</span>
</label>
))}
</_RadioGroup>
)
})
```
After adding `getFieldName` to `FormField`, we can retrieve the field name by:
```
const { fieldApi: { getFieldName } } …
```
=> Add getFieldName to fieldApi for getting field name of custom input

src/redux/utils.js
This try-catch impacts hugely on performance for big forms. After profiling and removal, my input updates become faster about 3 times. But performance is still not very good due to full form re-rendering
=> Make it faster for big forms

src/redux/utils.js
https://github.com/react-tools/react-form/pull/206 removed a try/catch in the `get` utility function. This try/catch had been previously swallowing errors when it tried to access a value on `null`.
=> Prevent error that had been previously swallowed by try/catch

dev/Intro.js, src/components/ReduxForm.js, test/components/ReduxForm.spec.js
This allows to handle `onSubmit` errors in `onSubmitFailure`, e.g.,
```jsx
onSubmit={async (result) => {
await fetchData('/api', result);
}}
onSubmitFailure={(validationErrors, formApi, fetchError) => {
this.setState({ fetchError, validationErrors });
}}
```
=> catch errors during onSubmit

src/components/form-fields/Select.js
Hi,
I'd like to have the possibility not to have any placeholder on selects for fields that always have a default and no possible empty values
I think passing placeholder={false} to selects makes sense
if this is ok for you can we publish it as a 2.x release?
=> Allow passing false to select placeholder option

src/components/form-fields/Radio.js, tests/components/form-fields/Radio.spec.js
Hello, while testing Radio inputs using capybara, we could see that the inputs all have `value="on"`.
We would like to have the value passed to the input vanilla.
=> Radio input value

src/components/Form.js, tests/components/Form.spec.js
Hello, we use react-form in one of our project.
With an array-field when we remove value, we could see that the errors where not updated.
Here is a fix.
I also took some liberty to add a small refactor commit.
Just tell me what do you think of this one, as it is not necessary (the real fix is in the first commit).
=> Form removeValue should reset errors

src/components/Form.js
When asyncValidate is used, onSubmit is never called.
What happens is the following line doesn't wait for validation to complete, it passes through it because the async validation functions are not returned.
https://github.com/react-tools/react-form/blob/807ece395d54e51783155398211bc54d3e16e3ba/src/components/Form.js#L381
=> Fixed asynValidate bug not calling onSubmit prop

src/components/Field.js
The other field options are excluded as props, but preValidate is not. When defining preValidate on a field, React complains with: "Unknown prop `preValidate` on <input> tag." This excludes preValidate as well.
=> Excluded preValidate from component props.

package.json
This library (though officially not maintained) works fine in React 17
The reasoning for this is because NPM v7 installs peerDependencies by default. The only way to get around the conflict when using this library and React 17 is to append `--legacy-peer-deps`
=> Add React 17 support

docs/comparison.md
When browsing the [Comparision page](https://tanstack.com/form/latest/docs/comparison) I noticed the badge link to GitHub and the image URL were incorrect:
This PR fixes it by changing `tannerlinsley/@tanstack` and `@tanstack` to `TanStack`.
=> fix: links from star badge to github

babel.config.js, docs/reference/fieldApi.md, examples/react/simple/src/index.tsx, packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/react-form/src/useField.tsx, packages/react-form/src/useForm.tsx
- Fix type of `ChangeProps.onChange`
- Fix basic react example `<form.Subscribe>` to get type inference working
- Fix build error by removing unused `validateForm()` method
- Fix the build by adding a few `as any` on react-store errors that I don't understand
- Fix the below `pnpm test:build` error by adding `['@babel/plugin-proposal-class-properties', { loose: false }]` to the babel config
```
[!] Error: Private field '#prevState' must be declared in an enclosing class (Note that you need plugins to import files that are not JavaScript)
packages/form-core/src/FieldApi.ts (116:35)
114:             : undefined
115: 
116:           if (state.value !== this.#prevState.value) {
^
117:             this.validate('change', state.value)
118:           }
Error: Private field '#prevState' must be …
```
=> fix several type  and build errors and fix example type inference

packages/form-core/src/FormApi.ts, packages/form-core/src/tests/FormApi.spec.tsx, packages/form-core/src/tests/test.test.tsx, packages/form-core/src/utils.ts
=> Fix minor FormApi bugs and add initial form API tests

packages/form-core/src/FieldApi.ts
When running validation, there were some errors about maximum depth being exceeded. I fixed this by moving the validation check out of the stores' `onUpdate` and into the `setValue` function itself. It's not perfect, but I think this might honestly just be the way to go to sidestep this issue.
At very least it solves the issue in the short term so we can keep writing tests and stabilizing the API
Closes #406
=> fix: maximum depth exceeded should no longer occur on validation

.github/workflows/pr.yml
Per @ZackDeRose:
> ok, so this is because the command is using nx affected, but you haven't checked out all the branches
> nx affected compares git commits to see if a package could be affected
> easy fix: skip affected
>
>harder fix: pull down all the relevant branches
> I think query has an example
This seems like it may fix the issue we're experiencing with CI
=> chore: attempt to fix test build CI command

packages/form-core/src/tests/FieldApi.spec.ts
This PR adds a test for the `onChange` validation method on the core.
=> test(form-core): add onChange validation test

packages/form-core/src/FieldApi.ts, packages/form-core/src/tests/FieldApi.spec.ts
While writing tests for onChange validation in the react adapter, I noticed that the default meta wasn't being passed to the field. This PR aims to fix that
=> fix(form-core): allow set default field meta

package.json, packages/form-core/package.json, packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/form-core/src/tests/FieldApi.spec.ts, packages/form-core/src/tests/FormApi.spec.ts, packages/react-form/package.json, packages/react-form/src/tests/useField.test.tsx, pnpm-lock.yaml
Recently, [we migrated `@tanstack/store` packages to a dedicated repo](https://github.com/TanStack/store). When we did so, we shifted some of the behavior (to fix bugs in the package, shown through testing). 
This PR:
=> Update `store` packages to match dedicated repo

packages/react-form/src/createFormFactory.ts
What this PR aims to:
- Small improvement in the fieldOptions object: change _Spread Operator_ to _Object.assign_.
- with this even if receive anything that's not a object will not be appended 😎
=> refactor: change form options spread to object assign

docs/framework/react/quick-start.md, docs/framework/react/reference/formApi.md, docs/guides/basic-concepts.md, docs/overview.md, docs/reference/fieldApi.md, examples/react/simple/src/index.tsx, examples/react/simple/tsconfig.json, packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/react-form/src/index.ts, packages/react-form/src/tests/createFormFactory.test.tsx, packages/react-form/src/tests/useField.test.tsx, packages/react-form/src/tests/useForm.test.tsx, packages/react-form/src/useForm.tsx, tsconfig.json
This PR aims to solve React Native support and make the code less runtime/UI reliant by removing all methods and types that utilized the DOM. This includes:
- Removing `APIForm.getFormProps()`
- Removing `APIField.getInputProps()`
- Removing `APIField.getChangeProps()`
- Changing `APIForm.handleSubmit()` to remove `e` argument
- Adding a new `APIField.handleChange()` to call on an input by: `onChange={e => field.handleChange(e.target.value)}`
- Adding a new `APIField.handleBlur()` to call on an input by: `onBlur={field.handleBlur}`
While this might seem like a more verbose syntax, it brings a few additional benifits:
- Avoids headaches with typings for UI libraries like React Aria or ShadCN/UI that might not use exact `input` or similar under-the-hood.
- Allows us more flexibility if UI …
=> Make runtime agnostic/Support React Native

packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/form-core/src/tests/FieldApi.spec.ts, packages/form-core/src/tests/utils.ts
This PR adds tests to the validations API (`onChangeAsync`, `onBlur`, `onBlurAsync`, `onSubmitAsync`) and with debounce as well. Also remove old `asyncDebounceMs` API
=> [Form Core] Add tests to the validations API and remove `asyncDebounceMs`

packages/form-core/src/FieldApi.ts, packages/form-core/src/tests/FieldApi.spec.ts
`update` was being called before `mount` which was causing the listeners in `mount` to never call to update `this.state`.
This PR was halting progress on the Vue adapter
=> fix: Field default should now be set properly

examples/vue/simple/package.json, examples/vue/simple/src/App.vue, packages/form-core/tsconfig.eslint.json, packages/react-form/package.json, packages/react-form/src/useField.tsx, packages/react-form/src/useForm.tsx, packages/react-form/src/utils/isBrowser.ts, packages/react-form/src/utils/useIsomorphicLayoutEffect.ts, packages/react-form/tsconfig.eslint.json, packages/react-form/tsup.config.js, packages/vue-form/tsconfig.eslint.json, packages/vue-form/tsup.config.js, pnpm-lock.yaml
This PR fixes bundler issues with React and Vue as well as an issue with using `browser` in React Native for a hook
=> fix: bundler errors in React and Vue adapters should now be resolved

.github/workflows/ci.yml, .github/workflows/pr.yml
This PR bumps CI/CD to use a newer version of Node/etc
=> chore: bump CI/CD

docs/framework/vue/quick-start.md, examples/vue/simple/src/App.vue, packages/vue-form/src/tests/useField.test.tsx, packages/vue-form/src/tests/useForm.test.tsx, packages/vue-form/src/useField.tsx, packages/vue-form/src/useForm.tsx
Hi! This PR adds typings to the `Subscribe` and `Field` component default slot values.
Some reference: https://github.com/vuejs/core/pull/7982
Tests passed ✅
=> fix(vue): Component default scoped slot value types

packages/form-core/src/FieldApi.ts, packages/form-core/src/tests/FieldApi.spec.ts
This PR fixes an issue that was introduced in `0.3.0` that led to `onChange` causing issues when new input was typed
=> fix: onChange should disappear when new input comes in

docs/framework/react/quick-start.md
Align the "quick-start" example and "simple" example. Fix misleading doc code example.
=> docs(quick-start): add <form> tag to quick start example

packages/form-core/src/FieldApi.ts, packages/form-core/src/tests/FieldApi.spec.ts, packages/react-form/src/tests/useField.test.tsx, packages/vue-form/src/tests/useForm.test.tsx
Set the form's value when creating a field with defined default value.  Close #435
=> fix: field `defaultValue` should precedence over form `defaultValues`

packages/form-core/src/FormApi.ts, packages/form-core/src/tests/FormApi.spec.ts
Field just update meta `errorMap` when error change. The value of form is the previous value.
Close #464
=> fix: form's valid state should be work fine

packages/react-form/package.json, packages/react-form/src/useField.tsx, packages/react-form/src/useForm.tsx, packages/react-form/src/useIsomorphicLayoutEffect.ts, pnpm-lock.yaml, tsconfig.base.json
Issue: https://github.com/TanStack/form/issues/470
The [use-isomorphic-layout-effect](https://github.com/Andarist/use-isomorphic-layout-effect) package seems to cause issues on NextJS.
See the detailed investigation [here](https://github.com/TanStack/form/issues/470#issuecomment-1777837403). 
TL;DR it may be a NextJS issue or an issue with `use-isomorphic-layout-effect` (it seems adding an "exports" section to its package.json file fixes the issue).
We only use the `useIsomorphicLayoutEffect` hook from that package and since its implementation is a one-liner, I've added it to `react-form`, which fixes the nextjs issue.
=> fix: remove use-isomorphic-layout-effect package for nextjs compatibility

docs/guides/validation.md
Issue: https://github.com/TanStack/form/issues/477
Add more info to the validation guide page.
While working on this, I've identified a few issues and inconsistencies. I'll probably create issues and discussion topics about these, but listing them here first in case I've missed some things:
formAPI's `onChange` doesn't seem to be called at all and it expects the same return type as fieldAPI's `onChange`. If we want to allow doing validation at the form level in `onChange`, we probably need it to return a mapping of errors per field (same with onBlur and async methods).  [Here](https://codesandbox.io/p/sandbox/determined-mayer-yn4qfc?file=%2Fsrc%2Findex.tsx%3A43%2C29) is a repro of this.
As I have mentioned in the docs, it seems that the way to prevent submission of untouched forms is to …
=> docs(validation): Improved validation guide

docs/guides/validation.md
Invalid MDX comment was breaking page at [https://tanstack.com/form/latest/docs/guides/validation](url).
**Error message:** ```Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)'```
=> docs: fix invalid mdx comment syntax

packages/form-core/src/FormApi.ts, packages/form-core/src/tests/FormApi.spec.ts, packages/react-form/src/tests/useForm.test.tsx, packages/react-form/src/useForm.tsx, packages/solid-form/src/createForm.tsx, packages/solid-form/src/tests/createForm.test.tsx, packages/vue-form/src/tests/useForm.test.tsx, packages/vue-form/src/useForm.tsx
As discussed in #493 
Edit:
Should mention that `onMountAsync` and `onMountAsyncDebounceMs` were removed since onMount callbacks should only run once.
=> feat: mount method on FormApi

packages/form-core/src/FieldApi.ts, packages/form-core/src/tests/FieldApi.spec.ts
This adds tests for #502 and closes #502.
=> Added tests to illustrate a bug and fix it ;) 

packages/form-core/src/FormApi.ts
This PR fixes an error that was introduced in #505, which I did not catch prior to merging. Sorry y'all!
=> fix: errors should no longer throw on intial render

docs/reference/formApi.md, pnpm-lock.yaml
Fix a small typo by changing 'yonu' to 'your' in `formApi.md`.
No breaking changes.
=> docs(formApi.md): Fix a small typo by changing 'yonu' to 'your'

docs/reference/formApi.md
The TanStack Store instance has some useful methods of its own. It may be helpful to provide a link to its docs from here.
=> docs(FormApi): Include link to TanStack Store docs beneath FormApi's Store instance

docs/reference/fieldApi.md
- Fixes a typo on the `FieldApi` API reference page.
=> fix(docs): fix typo on the fieldApi reference

CONTRIBUTING.md
Update CONTRIBUTING.md with instructions for previewing the documentation locally.
=> Preview the docs locally

.prettierignore, .prettierrc, codecov.yml, examples/react/simple/.eslintrc.cjs, examples/react/simple/index.html, examples/react/simple/src/index.tsx, examples/react/valibot/.eslintrc.cjs, examples/react/valibot/index.html, examples/react/valibot/src/index.tsx, examples/react/yup/.eslintrc.cjs, examples/react/yup/index.html, examples/react/yup/src/index.tsx, examples/react/zod/.eslintrc.cjs, examples/react/zod/index.html, examples/react/zod/src/index.tsx, examples/solid/simple/src/index.tsx, examples/vue/simple/index.html, examples/vue/simple/src/App.vue, examples/vue/valibot/index.html, examples/vue/yup/index.html, examples/vue/zod/index.html, package.json, packages/form-core/src/FieldApi.ts, packages/form-core/src/utils.ts, pnpm-lock.yaml, prettier.config.js, tsconfig.json
Use script and config from query repo
=> chore: Update prettier config

packages/form-core/package.json, packages/form-core/vite.config.ts, packages/react-form/package.json, packages/react-form/vite.config.ts, packages/solid-form/package.json, packages/solid-form/vite.config.ts, packages/valibot-form-adapter/package.json, packages/valibot-form-adapter/vite.config.ts, packages/vue-form/vite.config.ts, packages/yup-form-adapter/package.json, packages/yup-form-adapter/vite.config.ts, packages/zod-form-adapter/package.json, packages/zod-form-adapter/vite.config.ts
`vitest --typecheck` runs all type tests _and_ all normal tests. It makes more sense to run these as a single task under `test:lib`. The Vite config has been updated to enable coverage and type tests without needing CLI flags.
=> chore: Avoid running Vitest twice

.github/workflows/ci.yml, .github/workflows/pr.yml
`codecov/codecov-action@v3` would scan the `.nx/cache` directory and upload coverage reports from here, which could mess with accuracy. Logic copied from query repo.
=> ci: Avoid uploading coverage files in Nx cache

package.json, pnpm-lock.yaml, scripts/publish.js, tsconfig.json
On successfully finishing the script, this github workflow continued indefinitely: https://github.com/TanStack/form/actions/runs/7419873463
This seems to be an async/await error. I'm expecting this change (https://github.com/TanStack/config/releases/tag/v0.1.7) will allow it to correctly return exit code 0.
I've tweaked the tsconfig file to use `"module": "ES2022"`, since this permits top-level await. This has no impact on the types generated for packages.
=> fix: Correctly exit publish script

tsconfig.json
- Disabled `allowUnreachableCode` and `allowUnusedLabels`
- Enabled `noUnusedParameters`
- Added `noUnusedLocals` to enable once issues are fixed
- Removed `strictNullChecks` (covered by `strict`)
- Removed `baseUrl` (no longer used to resolve packages)
=> chore: Stricter tsconfig options

packages/form-core/src/tests/utils.spec.ts, packages/form-core/src/utils.ts
Hit this issue when I had a nested field on a field that didn't have a default value set up.
=> fix: delete non-existent fields without errors

docs/guides/basic-concepts.md
There was an extra semicolon which seems like a typo. Removed it.
=> Remove typo basic-concepts.md

nx.json
The Nx setup doesn't use the `@nrwl/js` plugin, so this is redundant
=> ci: Remove Nx `pluginsConfig` option

docs/framework/react/reference/formApi.md, packages/react-form/package.json, packages/react-form/src/useForm.tsx, packages/react-form/tsconfig.50.json
We run into a bug in older TypeScript versions in another PR. See [this discussion](https://github.com/TanStack/form/pull/606#discussion_r1506715714) for a detailed report and the solution we decided on.
**TODO**
[0] This is how the comment is rendered:
https://github.com/TanStack/form/assets/43729152/ecf52d2f-2ff9-4393-a9a6-c9e6ed3a9b45
=> Handle a bug in older versions of TypeScript (<5.1.6)

package.json, packages/react-form/tsconfig.json, packages/react-form/tsconfig.legacy.json, packages/solid-form/tsconfig.json, packages/solid-form/tsconfig.legacy.json, packages/valibot-form-adapter/tsconfig.json, packages/valibot-form-adapter/tsconfig.legacy.json, packages/vue-form/tsconfig.json, packages/vue-form/tsconfig.legacy.json, packages/yup-form-adapter/tsconfig.json, packages/yup-form-adapter/tsconfig.legacy.json, packages/zod-form-adapter/tsconfig.json, packages/zod-form-adapter/tsconfig.legacy.json, pnpm-lock.yaml
- "Go to source" will now take you to the source `.ts` rather than the dist `.js` or `.d.ts`
- Can run project tasks (e.g. build react-form) without needing dependencies (i.e. form-core) to be built first
- Related PR: https://github.com/TanStack/config/pull/63
=> chore: Use tsconfig paths to improve local DX

packages/angular-form/src/tanstack-field.directive.ts
Fix: #645
This is the quickest, closest-to-how-Angular-does-it fix. It does allow _any_ value as an input, however:
| Input value | Previous result | New result |
|---|---|---|
| **Boolean transform** | | |
| `[asyncAlways]="true"` | `true` | `true` |
| `[asyncAlways]="false"` | `false` | `false` |
| `asyncAlways` | Error (should be `true`) | `true` |
| `asyncAlways="true"` | Error (should be `true`) | `true` |
| `asyncAlways="false"` | Error (should be `false`) | `false` |
| `asyncAlways="fasle"` | Error | `true` (should be an error) |
| **Number transform** |||
| `[asyncDebounceMs]="500"` | `500` | `500` |
| `asyncDebounceMs="500"` | Error (should be `500`) | `500` |
| `asyncDebounceMs` | Error | `NaN` (should be an error) |
| `asyncDebounceMs="123abc"` | Error | `NaN` (should be an …
=> fix: transform valid values for number and boolean HTML attributes

docs/framework/react/guides/basic-concepts.md, packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/form-core/src/tests/FieldApi.spec.ts
=> feat: add array fields move method

packages/form-core/src/tests/utils.spec.ts, packages/form-core/src/utils.ts
Fixes #657 
I added a few tests and used it on a local project to check if it was working
=> fix: extract path from nested arrays

docs/config.json, docs/framework/react/guides/linked-fields.md, docs/reference/fieldApi.md, examples/react/simple/src/index.tsx, packages/form-core/src/FieldApi.ts, packages/form-core/src/tests/FieldApi.spec.ts, packages/form-core/src/utils.ts, packages/react-form/src/tests/useField.test.tsx
This PR adds an initial implementatin of linked fields into TanStack Form. The usage looks something like this:
```tsx
<div>
<form.Field
name="password"
children={(field) => (
// ...
)}
/>
</div>
<div>
<form.Field
name="password_confirm"
validators={{
onChangeListenTo: ['password'],
onChange: ({ value, fieldApi }) =>
fieldApi.form.getFieldValue('password') === value ? undefined : 'Passwords do not match'
}}
children={(field) => {
// ...
}}
/>
</div>
```
=> feat: add initial implementation of linked fields

examples/angular/simple/src/app/app.component.ts, examples/react/simple/src/index.tsx, packages/form-core/src/FormApi.ts, packages/form-core/src/tests/FormApi.spec.ts
PR should fix issue #671 
The new behavior now respects whatever is inside the fieldMeta but resetting any validation that the field might have, as well added the reset button to React and Angular examples (it might need to be added or not to more examples) and i added a single test.
=> fix(formApi): prevent reset from wiping validators in fieldMeta

packages/form-core/src/tests/util-types.test-d.ts, packages/form-core/src/util-types.ts
- Ensure termination of recursive type when `any` is passed to it
- Eliminate depth as this is not necessary
=> perf: terminate infinite recursion of DeepValue when `any` is passed

packages/form-core/src/FieldApi.ts, packages/react-form/src/tests/useField.test.tsx
This PR fixes #685, which was a result of a bug in `form-core` accessing the `name` field naively
=> fix: nested values should not disappear in strictmode

docs/reference/fieldApi.md, packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/form-core/src/tests/FieldApi.spec.ts
=> fix(core): re-validate the subfields after one of them have been removed

docs/framework/react/guides/ssr.md
Noticed this typo when going through docs and wanted to send a quick fix
=> fix(ssr-docs): Corrected "intergration" to "integration" in SSR docs

packages/form-core/src/tests/FormApi.spec.ts, packages/form-core/src/utils.ts
My previous PR added support for nullable objects on type level.
Didn't check if updating a null object works or not.
This PR adds tests and fixes this issue.
=> feat: add support for nullable objects.

packages/react-form/src/tests/useField.test-d.tsx, packages/react-form/src/types.ts, packages/react-form/src/useField.tsx, packages/react-form/src/useForm.tsx
This is a first: React's types conditionally export a different version for 4.9 and 5.0:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/package.json#L10-L15
Among the changes between 4.9 and 5.0 appear to be a mismatch between React.JSX.Element and React.ReactNode, which was causing a failure in our build/TypeScript 4.9 support.
This PR replaces usages of `ReactNode` and `React.JSX.Element` with a custom type of:
```typescript
export type NodeType = ReturnType<FunctionComponent>
```
Which solves this incompatibility, while retaining our strict types.
=> chore: fix React TSC usage for 4.9

examples/angular/valibot/angular.json, examples/angular/valibot/package.json, examples/angular/valibot/src/app/app.component.ts, examples/angular/valibot/tsconfig.json, examples/react/valibot/package.json, examples/react/valibot/src/index.tsx, examples/react/valibot/tsconfig.json, examples/solid/valibot/package.json, examples/solid/valibot/src/index.tsx, examples/vue/valibot/package.json, examples/vue/valibot/src/App.vue, packages/valibot-form-adapter/package.json, packages/valibot-form-adapter/src/tests/FieldApi.spec.ts, packages/valibot-form-adapter/src/tests/FieldApi.test-d.ts, packages/valibot-form-adapter/src/tests/FormApi.spec.ts, packages/valibot-form-adapter/src/tests/FormApi.test-d.ts, packages/valibot-form-adapter/src/validator.ts, packages/valibot-form-adapter/tsconfig.json, pnpm-lock.yaml
https://valibot.dev/guides/migrate-to-v0.31.0/
=> Upgrade and migrate Valibot to v0.31.0

.github/ISSUE_TEMPLATE/config.yml
The previous link was pointing to an archived channel, the new one is the link used everywhere else in the docs pointing to #💬-introductions
=> docs: update discord invite link

packages/form-core/src/tests/util-types.test-d.ts, packages/form-core/src/util-types.ts
fix https://github.com/TanStack/form/issues/738
Typescript will see `{a?:number}` as `{ a: number | undefined } | {}`, so `object extends T` will return `true`.
Which cause `DeepKeys<{a?:number}>` go to `PrefixFromDepth<string, TDepth>`, returns `string`.
**Danger**: Delete it will cause `DeepKeys` handle other types: like `class`. I don't know if this is expected.
```ts
class SomeClass {
someAttribute = "hello world";
someFunction() {
return this.someAttribute;
}
}
type A = DeepKeys<{ a: SomeClass; b: string }>; // "a" | "b" | "a.someAttribute" | "a.someFunction"
```
In `PrefixObjectAccessor` type, if `K` is partial, `T[K]` will union with `undefined`. So `PrefixObjectAccessor` result will get `undefined`.
=> fix(core): fix DeepKeys not support partial nested object

examples/react/next-server-actions/package.json, nx.json
The Next server actions example is having issues due to pnpm resolution of the global React 18 types and its local React 19 RC types:
`Type 'import("/home/workflows/workspace/node_modules/.pnpm/@types+react@18.3.3/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'`
This PR temporarily disables its type checking until the React 19 release
=> chore: Temporarily disable type checking for Next.js example

packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/react-form/tests/useField.test.tsx
This PR solves issues with StrictMode and arrays as outlined by #704.
Fixes #704
=> fix: issues with StrictMode and arrays are now solved

examples/lit/simple/tsconfig.json, examples/lit/ui-libraries/tsconfig.json, examples/react/next-server-actions/tsconfig.json, examples/react/ui-libraries/tsconfig.json, examples/solid/array/tsconfig.json, examples/solid/simple/tsconfig.json, examples/solid/valibot/tsconfig.json, examples/solid/yup/tsconfig.json, examples/solid/zod/tsconfig.json, examples/vue/array/tsconfig.json, examples/vue/simple/tsconfig.json, examples/vue/valibot/tsconfig.json, examples/vue/yup/tsconfig.json, examples/vue/zod/tsconfig.json, packages/angular-form/tsconfig.build.json, packages/angular-form/tsconfig.json, packages/form-core/tsconfig.legacy.json, packages/react-form/tsconfig.legacy.json, packages/solid-form/tsconfig.legacy.json, packages/valibot-form-adapter/tsconfig.legacy.json, packages/vue-form/tsconfig.legacy.json, packages/yup-form-adapter/tsconfig.legacy.json, packages/zod-form-adapter/tsconfig.legacy.json, tsconfig.json
Fixes errors resolving imports in top-level type-checked files such as `eslint.config.js`
=> chore: Set root "moduleResolution" to "Node"

examples/angular/valibot/package.json, examples/react/valibot/package.json, examples/solid/valibot/package.json, examples/vue/valibot/package.json, packages/valibot-form-adapter/package.json, pnpm-lock.yaml
Unfortunately, I introduced a breaking change in a type of Valibot v0.33.0. So I updated the dependencies.
=> chore: Update valibot dependency to version >=v0.33.0

packages/react-form/src/createServerValidate.ts, packages/react-form/src/useField.tsx, packages/react-form/src/useForm.tsx, packages/solid-form/src/createField.tsx, packages/solid-form/src/createForm.tsx, packages/vue-form/src/useField.tsx, packages/vue-form/src/useForm.tsx
Previously, we were patching the types of `form-core` in our framework adapters, which meant that any imports to `@tanstack/form-core` would _technically_ not be correct. This PR fixes this by localizing these imports and making them more accurate.
=> fix: Remove `form-core` type overrides from adapters

packages/form-core/src/FieldApi.ts, packages/form-core/tests/FieldApi.spec.ts
The async validator (arriving late by its nature) overrides the result of the sync validator, ending up in a valid component when async is valid but sync is not.
With debounce:
1. Input a valid value for the sync validator
2. Async validator is _enqueued_
3. Input an invalid value for the sync validator
4. Async validator _is called_ and when resolves if valid removes the errors
Without debounce, but async takes some time:
1. Input a valid value for the sync validator
2. Async validator _is called_
3. Input an invalid value for the sync validator
4. Async validator _resolves_ and if valid removes the errors
It's easy to reproduce in the [simple example](https://tanstack.com/form/latest/docs/framework/react/examples/simple), by writing `aaaa` and waiting the async validator, then rapidly …
=> fix(core): abort async validation if sync validation fails in the meantime

packages/valibot-form-adapter/tests/FieldApi.spec.ts, packages/yup-form-adapter/tests/FieldApi.spec.ts, packages/zod-form-adapter/tests/FieldApi.spec.ts
I'm not sure why [this test failed](https://github.com/TanStack/form/actions/runs/9738060935/job/26871065053#step:5:554) on the CI but not locally.
Giving it a try with an actual async operation to be awaited.
=> test: fix async validation tests with adapters

docs/overview.md
Let's make this official offical.
=> docs: announce the RC phase in overview docs

examples/angular/array/package.json, examples/angular/simple/package.json, examples/angular/valibot/package.json, examples/angular/yup/package.json, examples/angular/zod/package.json, examples/lit/ui-libraries/package.json, examples/react/query-integration/package.json, packages/lit-form/package.json, packages/react-form/package.json, pnpm-lock.yaml
- Used [manypkg](https://github.com/Thinkmill/manypkg) to identify issues with deps/devDeps/peerDeps
- The only actual change is adding `"lit"` as a devDep to the lit-form package (allows the peerDep to be a different range to what is installed in this repo)
- The other changes are just alphabetical sorting
=> fix(lit-form): Correct deps/devDeps/peerDeps

docs/framework/react/guides/ssr.md, examples/react/tanstack-start/app/routes/index.tsx, examples/react/tanstack-start/app/utils/form.tsx, packages/react-form/src/start/getFormData.tsx
There was a bug in our TanStack Start adapter that led to headaches. This PR fixes those but introduces a minor breaking change where Start users need to use `createServerFn` now alongside `getFormData`
=> feat: force createServerFn usage with getFormData

packages/solid-form/package.json, packages/solid-form/tsconfig.build.json, packages/solid-form/vite.config.ts
This implements the changes discussed on Corbin's stream with Ryan.
- `esm` and `cjs` builds are now generated again for use in no-build environments
- The JSX-preserving build is now generated in `source`, keeping with Solid ecosystem conventions
- The `source` entrypoint is still `.jsx` to make sure that all JSX gets compiled properly
=> fix(solid-form): Build ESM, CJS, and source

docs/framework/angular/guides/arrays.md, docs/framework/angular/guides/basic-concepts.md, docs/framework/angular/guides/validation.md, docs/framework/angular/quick-start.md
Shikijs supports [TypeScript](https://github.com/shikijs/textmate-grammars-themes/blob/main/packages/tm-grammars/grammars/angular-ts.json) and [HTML](https://github.com/shikijs/textmate-grammars-themes/blob/main/packages/tm-grammars/grammars/angular-html.json) dialects, which improves the syntax highlighting for the Angular samples.
=> docs: update the syntax highlighting for angular

docs/framework/angular/guides/arrays.md, docs/framework/angular/guides/basic-concepts.md, docs/framework/react/guides/arrays.md, docs/framework/react/guides/basic-concepts.md, docs/framework/react/guides/linked-fields.md, docs/framework/vue/guides/basic-concepts.md
This PR addresses several minor issues in the TanStack Form documentation:
1. **Basic Concepts Section**:
- Updated the snippet to use `meta` for `errors` and `isValidating` since they're not directly in `field.state`.
- New snippet: 
```javascript
const { value, meta: { errors, isValidating } } = field.state
```
2. **Arrays Guide**:
- Changed "Basic usage" subtopic header from `h1` to `h2` for better consistency.
3. **Linked Fields Guide**:
- Added an `id` and `title` to the markdown to match other sections.
Links to the issues:
- [Basic Concepts](https://tanstack.com/form/latest/docs/framework/react/guides/basic-concepts#field-state)
- [Arrays Guide](https://tanstack.com/form/latest/docs/framework/react/guides/arrays)
- [Linked …
=> docs: fix doc issues and header consistency

packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/form-core/tests/FieldApi.spec.ts, packages/form-core/tests/FormApi.spec.ts
This PR adds an ability to set errorMap on a fieldApi on formApi as requested in #786.
work done:
Feel free to reach out if any of the implementation made needs to be corrected.
=> Add 'setErrorMap' api to 'formApi' and 'fieldApi'

packages/react-form/src/useTransform.ts, packages/react-form/tests/useTransform.test-d.tsx
Passing the values (`fn` and `deps`) to `transform` works fine, it's just `useTransform` not being able to infer the `TFormData` properly.
=> fix: maintain the form types when transforming with useTransform hook

packages/react-form/src/nextjs/index.ts, packages/react-form/src/start/index.ts
Exports framework-specific types for TanStack Start and Next.js so they can be imported in apps that use them
Currently only `ServerFormState` type is exported but that will be in effect for all future types.
=> feat: export framework-specific types

packages/form-core/src/types.ts, packages/valibot-form-adapter/src/index.ts, packages/valibot-form-adapter/src/types.ts, packages/valibot-form-adapter/src/validator.ts, packages/valibot-form-adapter/tests/FieldApi.spec.ts, packages/yup-form-adapter/src/index.ts, packages/yup-form-adapter/src/types.ts, packages/yup-form-adapter/src/validator.ts, packages/yup-form-adapter/tests/FieldApi.spec.ts, packages/zod-form-adapter/src/index.ts, packages/zod-form-adapter/src/types.ts, packages/zod-form-adapter/src/validator.ts, packages/zod-form-adapter/tests/FieldApi.spec.ts
1. Adapters now share a common params interface to ensure consistency and making it easy to swap between them.
2. Return type exposed
`FormApi<FormData, ReturnType<typeof zodValidator>>` -> `FormApi<FormData, ZodValidator>`
=> refactor(adapters): improve coherence and expose return types

docs/framework/react/guides/react-native.md
In the React native example, it wasn't clear where `handleChange` came from
=> minor docs fix

packages/vue-form/src/useField.tsx, packages/vue-form/src/useForm.tsx
Much like in https://github.com/TanStack/form/pull/892 I'm working on wrappers in Vue for fields and it would be a great improvement if I could access these types.
edit: typo
=> Expose Vue specific interfaces

examples/angular/valibot/package.json, examples/react/valibot/package.json, examples/solid/valibot/package.json, examples/vue/valibot/package.json, packages/valibot-form-adapter/package.json, packages/valibot-form-adapter/src/validator.ts, pnpm-lock.yaml
I've updated the Valibot dependency on TanStack Form to v1. We've changed the type signature, so this change is necessary. All other changes in our v1 beta version are only internal.
---
An union of schema library authors (Zod, Valibot, ArkType, ...) collaborating on a standard interface for schema libraries called [Standard Schema](https://github.com/standard-schema/standard-schema). This simplifies implementation and prevents vendor lock-in. So far Valibot v1 supports this spec and Zod will follow soon. In the long run, the explicit implementation of a Valibot and Zod adapter may no longer be necessary.
=> chore: update valibot dependency to v1

docs/framework/react/guides/validation.md, examples/react/zod/src/index.tsx
Based on the discussion on https://github.com/TanStack/form/discussions/978 with @Balastrong 
This PR updates the docs example on `react/zod` using the most common case which is defining a `Zod` schema at the top level, and then using it on the `useForm` hook.
=> docs: update react-zod form example defining a zod schema

packages/valibot-form-adapter/package.json
Looks like the npm install broke with the upgrade to Valibot v1. This PR should fix that.
=> fix: Valibot peer dependency to support dist-tags

docs/reference/functions/mergeform.md, packages/form-core/src/mergeForm.ts, packages/form-core/tests/mutateMergeDeep.spec.ts
- this causes form submissions to be duplicated when having an array field in your form
Example of the problem: https://stackblitz.com/edit/tanstack-form-vdj4yh?file=src%2Fapp%2Fshared-code.ts
Just try to submit the form and watch the todos to be duplicated
=> fix: dont merge arrays in `mergeForm`

docs/reference/classes/formapi.md, packages/form-core/src/FormApi.ts, packages/form-core/tests/FormApi.spec.ts
This PR fixes #1027 
Form is already validated during field-level validation, no need to explicitly run it again on submit.
=> fix(core): run form submit validator once on submit

docs/framework/react/reference/functions/useform.md, docs/framework/react/reference/index.md, docs/framework/react/reference/type-aliases/reactformextendedapi.md, packages/react-form/src/index.ts, packages/react-form/src/useForm.tsx, packages/react-form/tests/useForm.test-d.tsx
=> fix: simplify useForm return type

docs/config.json, docs/framework/angular/guides/basic-concepts.md, docs/framework/angular/guides/listeners.md, docs/framework/angular/reference/classes/tanstackfield.md, docs/framework/react/guides/basic-concepts.md, docs/framework/react/guides/listeners.md, docs/framework/vue/guides/basic-concepts.md, docs/framework/vue/guides/listeners.md, docs/reference/classes/fieldapi.md, docs/reference/classes/formapi.md, docs/reference/index.md, docs/reference/interfaces/fieldapioptions.md, docs/reference/interfaces/fieldlisteners.md, docs/reference/interfaces/fieldoptions.md, docs/reference/interfaces/fieldvalidators.md, docs/reference/type-aliases/fieldmeta.md, docs/reference/type-aliases/fieldstate.md, packages/angular-form/src/tanstack-field.directive.ts, packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/form-core/tests/FieldApi.spec.ts, packages/form-core/tests/FormApi.spec.ts
**Background**
From discussion #709 and PR #801
A continuation of the PR #801 that been sitting stale since July, as per the previous pull request:
```
Sometimes we may want to attach our own side effects to the field when some event happens. 
For example, resetting another field if some field value has changed.
Attaching these 'listeners' inside the validator does not work as intended, because validator 
does not guarantee if it was triggered by the exact event. 
(eg. all validators run when form submits)
It's of course possible to implement, but it's not very clean and the concerns become scattered.
```
The PR was given the go ahead by @crutchcorn [here](https://github.com/TanStack/form/pull/801#issuecomment-2210348204).
This is something we would really like to have, as I'm currently …
=> feat(core): add field listeners

packages/form-core/src/utils.ts, packages/form-core/tests/FieldApi.spec.ts, packages/form-core/tests/utils.spec.ts
=> fix: handle numeric keys as array index only if parent is an array

examples/angular/array/package.json, examples/angular/simple/package.json, examples/angular/valibot/package.json, examples/angular/yup/package.json, examples/angular/zod/package.json, packages/angular-form/package.json, pnpm-lock.yaml
This PR drops support for Angular 17.3 and Angular 18.x
**This means that only Angular 19+ is supported**
This is a result of catching a very dangerous bug that was fixed using an Angular 19 API of `linkedSignal` that seemingly cannot be backported.
Immense apologies for this breaking change prior to 1.x
=> Drop Angular 17.3 and Angular 18.x support

docs/framework/angular/guides/basic-concepts.md, docs/framework/react/guides/basic-concepts.md, docs/framework/solid/guides/basic-concepts.md, docs/framework/vue/guides/basic-concepts.md
was removed by accident in #1064
@Balastrong sorry the "Schema Libraries" vs "Standard Schema Libraries" change slipped in with the one commit - renamed those Headlines as they only talk about the "Schema Libraries" that implement the "Standard Schema"
=> docs: re-add zod import in schema library example

examples/react/standard-schema/src/index.tsx, examples/react/standard-schema/tsconfig.json
there were a bunch ts-ignores, which looks bad on an example
Personally I prefer policing unused locals via a linter, which helps assign more appropriate "seriousness" to tsc errors, and so unused local errors can be more easily suppressed, but that's just me so I didn't make a sweeping change here.
=> chore: allow unusedLocals in standard-schema example

docs/reference/classes/fieldapi.md, packages/form-core/src/FieldApi.ts, packages/react-form/tests/useField.test.tsx
=> Fix an issue with conditionally rendered fields in React

docs/reference/classes/formapi.md, packages/form-core/src/FormApi.ts, packages/react-form/tests/useField.test.tsx
=> fix: meta should not regenerate every render

docs/installation.md
- Updated the installation documentation.
- Included package manager examples for:
- npm
- pnpm
- bun
- yarn
- Added installation commands for all four package managers for each framework adapter:
- React
- Vue
- Angular
- Solid
- Lit
- Provided examples for installing validator adapters:
- Zod
- Yup
- Valibot
=> docs: Add package manager examples for TanStack Form installation

docs/reference/classes/formapi.md, docs/reference/functions/shallow.md, docs/reference/index.md, docs/reference/interfaces/formoptions.md, docs/reference/interfaces/formvalidators.md, docs/reference/type-aliases/baseformstate.md, docs/reference/type-aliases/derivedformstate.md, docs/reference/type-aliases/fieldinfo.md, docs/reference/type-aliases/fieldserrormapfromvalidator.md, docs/reference/type-aliases/formstate.md, docs/reference/type-aliases/formvalidatefn.md, docs/reference/type-aliases/formvalidator.md, docs/reference/type-aliases/validationmeta.md, packages/form-core/src/FormApi.ts, packages/form-core/src/utils.ts, packages/react-form/tests/useForm.test.tsx
Fixes: https://github.com/TanStack/form/issues/1122
=> fix: useStore without a selector should no longer crash in React

docs/framework/react/guides/basic-concepts.md
From issue #1122 and a conversation with @crutchcorn, omitting the selector prop of the useStore hook will result in unnecessary re-renders.
---
The interface of useStore shows it as an optional prop, and while the hook will work without the prop, it is not the recommended approach.
```tsx
export declare function useStore<TState, TSelected = NoInfer<TState>>(store: Store<TState, any>, selector?: (state: NoInfer<TState>) => TSelected): TSelected;
```
---
I've searched the Docs for references to this, and the only documentation relating to this hook was under `Reactivity` of `basic concepts`. However, it does not highlight the risks of omitting selector.
The only other references to this hook, I found in the documentation, were examples demonstrating the use of `useStore`. However, none of …
=> feat(docs): risks of omitting useStore selector

docs/reference/classes/formapi.md, docs/reference/type-aliases/anyformapi.md, docs/reference/type-aliases/anyformstate.md, docs/reference/type-aliases/baseformstate.md, docs/reference/type-aliases/derivedformstate.md, docs/reference/type-aliases/formstate.md, examples/react/large-form/package.json, packages/form-core/src/FormApi.ts, packages/form-core/tests/FormApi.spec.ts, pnpm-lock.yaml
This adds a new prop the form state called `isSubmitSuccessful`. My use case for this is that there is no good way to keep input/submission disabled when a form that calls a server action which redirects the user when the form is successful.
=> feat: add isSubmitSuccessful prop

packages/form-core/src/metaHelper.ts, packages/form-core/tests/FieldApi.spec.ts
=> fix: subfield data is removed properly when calling removeFieldValue

docs/reference/classes/formapi.md, packages/form-core/src/FormApi.ts, packages/form-core/tests/FieldApi.spec.ts
Thanks to @LeCarbonator for the report and test
=> fix: deletion of subitems on a field now works

docs/philosophy.md
Unless there was a reason for h1s, I just converted headings to h2 to be consistent with the rest of the tanstack docs
=> docs(form-core): Update philosophy heading tag levels h1 to h2.md

docs/config.json, docs/framework/react/guides/custom-errors.md
Hello @crutchcorn  here are the docs for `custom errors`
for these docs i've used my example I created yesterday here, let me know if you need me to change something
```tsx
import { useState } from "react";
import { useForm } from "@tanstack/react-form";
function App() {
const [submittedData, setSubmittedData] = useState(null);
const form = useForm({
defaultValues: {
username: "",
age: 0,
email: "",
password: "",
},
validators: {
// Example 1: String error values
onChange: ({ value }) => {
return {
fields: {
username:
value.username && value.username.length < 3
? "Username must be at least 3 characters"
: undefined,
email:
value.email && !value.email.includes("@")
? "Email must contain @"
: undefined,
},
};
},
// Example 2: Non-string error values
onBlur: ({ value }) => {
return {
fields: …
```
=> docs: adding custom errors docs

docs/framework/react/guides/form-composition.md
Fix a minor typo in the documentation in the form-composition.md file
=> docs: fix typo in form-composition.md

docs/framework/react/guides/reactivity.md
I found some strange code in the guide document and fixed it. Congratulations on the official launch!
=> fix code example typo in reactivity.md

docs/framework/react/guides/form-composition.md
The quick guides docs don't emphasise the importance of exporting and importing the same useFieldContext as the form context, which if not emphasised I'm pretty convinced will lead to unnecessary issues. This PR fixes that, plus a small typo.
=> docs(react): emphasise form composition exports

docs/reference/functions/formoptions.md, packages/form-core/src/formOptions.ts
Remove unused `FormAsyncValidateOrFn` and `FormValidateOrFn` imports from `formOptions.ts`. These types were not referenced in the file, and their removal improves code cleanliness without impacting functionality.
No functional changes.
=> style(form-core): remove unused imports

docs/framework/solid/reference/functions/createfield.md, docs/framework/solid/reference/functions/field.md, docs/framework/solid/reference/type-aliases/fieldcomponent.md, packages/solid-form/src/createField.tsx
it was using a weird createMemo hack. Solid has a { equals: false } now that will track regardless of any changes so we can avoid an unnecesary memo and array creation (yay)
=> fix(solid-form): use { equals: false }

examples/react/query-integration/src/index.tsx
Added a dummy DB and the support for showing how tanstack forms can be robust and maintain the data after updates/mutations and on refetch
Mentions issue: #1211 
Let me know if any issues with using the Dummy DB approach and whether there is a simpler way you find to show the robustness of data with tanstack-query.
=> docs(react): Added a dummy DB and the support for showing how tanstack forms can be robust

docs/framework/vue/quick-start.md
Instead of using the arrow function:
```vue
(e) => {
e.preventDefault()
e.stopPropagation()
form.handleSubmit()
}
```
we can just use [event modifiers](https://vuejs.org/guide/essentials/event-handling#event-modifiers) like this:
```vue
@submit.prevent.stop="form.handleSubmit"
```
enhancing readability ✨
=> docs(vue): use event modifiers to enhance readability

examples/react/tanstack-start/package.json, pnpm-lock.yaml
This PR eliminates the @tanstack/form-core package from the example, as it’s currently unused. If its functionality is needed, it's already [re-exported](https://github.com/TanStack/form/blob/v1.1.2/packages/react-form/src/index.ts#L1) from @tanstack/react-form. By dropping it, we avoid the hassle of keeping an extra package in sync with the adapter.
=> chore(deps): remove form-core package as it is unused and re-exported from react-form

docs/reference/classes/formapi.md, docs/reference/type-aliases/anyformapi.md, docs/reference/type-aliases/anyformstate.md, docs/reference/type-aliases/baseformstate.md, docs/reference/type-aliases/derivedformstate.md, docs/reference/type-aliases/formstate.md, packages/form-core/src/FormApi.ts
Adding a more explicit explanation for `form.onSubmit`
Triggered by the following question:
> Does `isSubmitted = true` imply that the `onSubmit` was successful?
=> docs(form): document relation of isSubmitted to onSubmit

examples/react/tanstack-start/app/client.tsx, examples/react/tanstack-start/app/router.tsx, examples/react/tanstack-start/app/routes/__root.tsx, examples/react/tanstack-start/app/ssr.tsx, examples/react/tanstack-start/app/utils/form-isomorphic.ts, packages/react-form/src/start/index.ts
Updates of imports:
TanStack/router has deprecated the ScrollRestoration, tanstack/start has renamed Meta to HeadContent, and moved Scripts from tanstack/start to tanstack/router
[x] meta -> HeadContent
[x] ScrollRestoration deprecated
[x] Scripts moved to tanstack/router
---
Export of formApi:
Form's tanstack/react-form/start docs show `// Notice the import path is different from the typical import location` however, tanstack/react-from/start dose not export formApi (like is done in tanstack/react-form/next) so `formOptions` isn't available from this path.
[x] export formApi from tanstack/react-form/start
=> fix(core, react): export formAPI and update imports for start Example

docs/framework/react/guides/ssr.md, examples/react/next-server-actions/src/app/action.ts, examples/react/remix/app/routes/_index/route.tsx, examples/react/tanstack-start/app/utils/form.tsx, packages/react-form/src/nextjs/createServerValidate.ts, packages/react-form/src/remix/createServerValidate.ts, packages/react-form/src/start/createServerValidate.tsx
Change serverValidate return type from `Promise<void>` to `Promise<TData>` to provide direct access to validated and parsed data. Eliminates the need to decode formData twice, enhancing developer experience with immediate typed access to validation results.
Closes #1317
=> feat(react-form): return parsed data from serverValidate function

docs/framework/react/guides/ssr.md, examples/react/tanstack-start/app/utils/form-isomorphic.ts, packages/react-form/src/start/index.ts
Exporting formOptions from start results in build error this PR reverts those changes and updated to docs to reflect this.
- revert export of form core
- updated SSR docs 
- updated tanstack start example
=> fix(core, react): export of formOptions results in build error

packages/react-form/src/start/getFormData.tsx
Removing the response header didn't do anything as the cookie had already been set on the client. This replaces it with the h3 deleteCookie method to ensure it actually gets deleted. Before this the error message would persist whenever the page was loaded.
=> fix(react-form): cookie deletion in getFormData

docs/framework/vue/quick-start.md
This PR corrects a TypeScript-related issue in the `quick-start.md` documentation file. The original example for the `<input>` event handler used `e.target.value` directly in the `@input` callback, which could cause TypeScript errors in an IDE due to the lack of type inference for `e.target`.
I updated the example to use `(e.target as HTMLInputElement).value`, aligning it with the correct implementation found in an example file in another directory. This ensures the documentation provides a TypeScript-safe code snippet for users.
- Updated the `@input` event handler example in `quick-start.md` from `(e) => field.handleChange(e.target.value)` to `(e) => field.handleChange((e.target as HTMLInputElement).value)`.
This change improves the accuracy of the `quick-start.md` documentation by …
=> docs(vue): fix TypeScript type assertion in quick-start.md input event handler example

docs/reference/classes/fieldapi.md, packages/form-core/src/FieldApi.ts, packages/react-form/tests/useField.test.tsx
It is impossible to remove an item from an array while properly using React keys.
Here is an [example](https://stackblitz.com/edit/tanstack-form-gcsxeyng?file=src%2Findex.tsx,src%2Fminimal.tsx) taken from the issue that demonstrates the problem. Try to remove the middle item.
This issue occurs because we use the ⁠index inside the field name. When you remove any item other than the last one, the array is re-iterated, and in the next render, the field names change.
In the current code, you update the name as the last action and use the old name in earlier actions. 
Let's assume you have an array:` ⁠[{ id: 1, name: "one"}, {id: 2, name: "two"}, {id: 3, name: "three"}]`, and you remove the middle item. In the next render loop, you want to render `⁠[{ id: 1, name: "one"}, {id: 3, name: …
=> fix(react-form): removing array items (#1171)

.github/workflows/autofix.yml
Having docs regenerated on each push on PR is handy but creates a lot of noise. Let's conditionally allow it only on main.
=> ci: skip doc generation on PR

docs/framework/react/guides/listeners.md, docs/reference/classes/fieldapi.md, docs/reference/interfaces/fieldapioptions.md, docs/reference/interfaces/fieldlisteners.md, docs/reference/interfaces/fieldoptions.md, docs/reference/interfaces/fieldvalidators.md, docs/reference/type-aliases/anyfieldapi.md, docs/reference/type-aliases/anyfieldmeta.md, docs/reference/type-aliases/anyfieldmetabase.md, docs/reference/type-aliases/anyfieldmetaderived.md, docs/reference/type-aliases/fieldmeta.md, docs/reference/type-aliases/fieldmetabase.md, docs/reference/type-aliases/fieldmetaderived.md, docs/reference/type-aliases/fieldstate.md, docs/reference/type-aliases/formvalidationerror.md, docs/reference/type-aliases/unwrapfieldasyncvalidateorfn.md, docs/reference/type-aliases/unwrapfieldvalidateorfn.md, packages/form-core/src/FieldApi.ts, packages/form-core/src/types.ts, packages/form-core/tests/FieldApi.spec.ts
This allows you to listen to a `change`/`blur` event of a Field after a denounce you can set in millisecond.
It makes situations possible where you want to introduce a side effect after the user stopped typing or left the field for some time.
=> feat(FieldApi): allow debounce of onChange and onBlur listener

docs/framework/react/guides/basic-concepts.md, docs/philosophy.md, examples/react/array/src/index.tsx
As discussed in the maintainers channel, updated the react docs to use type annotations instead of casting.
=> docs(react): use type annotations instead of casting

packages/form-core/src/util-types.ts
This is honestly super interesting. I noticed an explosion in instantiations based on one of the recent changes. Turns out checking if `TAccessor extends keyof TDeepRecord` blew up instantiations. But actually TS somehow can deduce `DeepKeys` can correctly index `DeepRecord` which doesn't blow up instantiations
I created a large object for a form to test instantiations. 
Before with `TAccessor extends keyof TDeepRecord`
```
Files:                         215
Lines of Library:            43159
Lines of Definitions:        80682
Lines of TypeScript:           490
Lines of JavaScript:             0
Lines of JSON:                   0
Lines of Other:                  0
Identifiers:                105841
Symbols:                     88523
Types:                        7296
Instantiations: …
```
=> fix(form-core): reduce instantiations

packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/form-core/src/metaHelper.ts, packages/form-core/src/types.ts, packages/form-core/src/utils.ts, packages/form-core/tests/FieldApi.spec.ts, packages/form-core/tests/FormApi.spec.ts, packages/form-core/tests/utils.spec.ts
Previously we were using a cumulative field errors map maintained at the form api level.
This PR removes that data structure in favor of a errorSourceMap data structure that lives within the FieldMeta for each field. This allows shifting/removing/deleting fields to automatically keep the errorSourceMap in sync.
This will fix https://github.com/TanStack/form/issues/1323 and prevent other bugs from being raised around validation not working after other array actions like removing, shifting, swapping, moving, etc...
Async validation & sync validation now is fully synced and thoroughly tested with the new errorSourceMap. This reduces the complexity of using the cumulative errors map significantly and fixes all the issues with validations running on the wrong fields when …
=> fix(form-core): fix broken sync/async validation logic

docs/config.json, docs/framework/svelte/guides/arrays.md, docs/framework/svelte/guides/async-initial-values.md, docs/framework/svelte/guides/basic-concepts.md, docs/framework/svelte/guides/linked-fields.md, docs/framework/svelte/guides/validation.md, docs/framework/svelte/quick-start.md, docs/installation.md
without reference docs for now because they can't be generated, as the generator doesn't know how to deal with Svelte imports
=> docs(svelte-form): add docs for svelte-form

packages/form-core/tests/FieldApi.test-d.ts, packages/form-core/tests/FormApi.test-d.ts, packages/form-core/tests/formOptions.test-d.ts, packages/form-core/tests/standardSchemaValidator.test-d.ts, packages/react-form/tests/createFormHook.test-d.tsx, packages/react-form/tests/useField.test-d.tsx, packages/react-form/tests/useForm.test-d.tsx, packages/react-form/tests/useTransform.test-d.tsx, packages/solid-form/tests/createField.test-d.tsx
Migrate all type tests to `expectTypeOf`
```ts
assertType<string>(0 as never) // <- no errors
expectTypeOf<string>(0 as never) // <- no errors
expectTypeOf(0 as never).toEqualTypeOf<string>() // <- flags the error
```
=> tests: replace assertType with expectTypeOf

packages/form-core/src/FormApi.ts
`onSubmitInvalid`: is 
the correct one: https://tanstack.com/form/latest/docs/reference/interfaces/formoptions#onsubmitinvalid
=> docs(form): fix mention of onSubmitInvalid

docs/framework/react/guides/listeners.md, packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/form-core/tests/FormApi.spec.ts
Adds form listeners to formApi.
=> feat(core): form listeners

docs/framework/react/guides/listeners.md, packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/form-core/tests/FormApi.spec.ts
Follow up from #1261, and the request made in issue #1261, from this [comment](https://github.com/TanStack/form/pull/1261#issuecomment-2833378957). This PR ads listeners debouncing at a form level.
=> feat(core): debounced form listeners

packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/form-core/src/utils.ts
Technically a breaking change on the types, but I feel manually setting derived meta (like `errors`) shouldn't be allowed as they would get overridden in the next update anyway.
=> fix: prevent manually setting derived meta

examples/react/field-errors-from-form-validators/src/index.tsx, packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/form-core/tests/FieldApi.spec.ts, packages/form-core/tests/FieldApi.test-d.ts, packages/form-core/tests/FormApi.spec.ts, packages/form-core/tests/FormApi.test-d.ts
At the current state the types of `form.setErrorMap` are wrong (asking for a validator function) and `field.setErrorMap` allows everything.
With this PR the allowed types are now exactly the ones coming from the defined validators to ensure type safety is correct when reading the values (e.g. from `field.getMeta().errors`)
=> fix: only allow setting manual errors according to the defined validators

packages/svelte-form/tsconfig.json
For some reason this generates .d.ts files on form-core when building svelte. I don't think this config is needed anyway as form-core is already from `workspace:*` in package.json
=> chore: remove svelte tsconfig explicit path to form-core

packages/form-core/src/utils.ts, packages/form-core/tests/utils.spec.ts
Closes #1488 
During parsing of the field name, multi-dimensional arrays (or names starting with an array access) were wrongly parsed in functions using `makePathArray` internally.
The side effects of this are listed in the linked issue, but to summarize, it wrongly interpreted array access as an object key, and that apparently lead to JavaScript silently converting the array into an object (classic ...)
The reason were mostly the regular expressions used to parse the field name, so test cases have been added and the function has been refactored.
```tsx
makePathArray('field[0][1].value') 
// == ['field', 0, '1', 'value']
```
```tsx
makePathArray('field[0][1].value') 
// == ['field', 0, 1, 'value']
```
There is now a lookahead used to avoid mismatches with subsequent numbers. Benchmarks …
=> fix(form-core): Fix  `setBy`/`getBy` not handling arrays properly

docs/framework/react/guides/form-composition.md
the docs does not clearly states that form.handleSubmit must be present in the subscribe button in form composition and will confuse many developers (and I did get confused). So with this it is clearly stated.
=> docs(react-form): add type=submit in form-composition.md subscribe button

examples/react/simple/src/index.tsx
I was playing with TanStack Form, starting from the simple example. I stumbled upon the annoying bug with `<select>` and form reset and found out that it's clearly documented here:
- https://tanstack.com/form/latest/docs/framework/react/guides/basic-concepts#reset-buttons
So this PR updates the simple example to follow the guidelines regarding form reset (which is to `event.preventDefault()`).
=> docs: follow guidelines for reset in simple example

packages/form-core/src/FormApi.ts, packages/form-core/tests/FormApi.spec.ts
This PR addesses the following issue: https://github.com/TanStack/form/issues/1559
💡 Open question: I don't know if other field array methods suffer from the same issue but, if some do, should we address those in this PR too?
=> fix(form-core): prevent `FormApi#moveFieldValues` from mutating `defaultValues`

packages/form-core/src/FieldApi.ts, packages/form-core/tests/FormApi.spec.ts
When both `onBlur` and `onChange` form listeners are provided with their own debounce delays (`onBlurDebounceMs`, `onChangeDebounceMs`), triggering one event shortly after the other results in only the last listener running. 
Example: [https://codesandbox.io/p/sandbox/zxyv5k](https://codesandbox.io/p/sandbox/zxyv5k)
Ways to reproduce:
1. Type something into input, then click outside of input to trigger blur event (only blur listener callback gets called)
2. Click into input, then out of it, then type something into input (only change listener callback gets called)
=> fix(form-core): prevent `onBlur` and `onChange` form listeners from canceling each other

packages/react-form/src/createFormHook.tsx, packages/react-form/tests/createFormHook.test-d.tsx
This PR fixes an issue that the previous generic had for interfaces in TypeScript.
`Record<string, unknown>` requires that any lookup must be possible using `obj[key]`, and since the generic extends it, it just means anything with an index signature.
Object literals obviously have an index signature already. And according to [this issue in the TypeScript repo](https://github.com/Microsoft/TypeScript/issues/15300), types also have an implicit type signature. However, interfaces can be extended at multiple locations, and therefore are not considered to have implicit signatures.
To put it simply, the code attempts to fix the following problem:
```tsx
// okay
withForm({
// ...
props: {  title: '' }
})
// okay
type FormProps = { title: string }
withForm({
// ...
props: {} as FormProps
})
// …
```
=> fix(react-form): Allow interfaces to be assigned to `withForm`'s `props`

packages/react-form/src/createFormHook.tsx, packages/react-form/src/useForm.tsx
Currently, with the following code:
```jsx
<AppForm>
<ContainerForm>
<AppField name="animal">
{() => <RadioGroupField {...props} />}
</AppField>
</ContainerForm>
</AppForm>
```
Storybook's "Show code" function displays "No Display Name" for `<AppForm>` and `<AppField>`:
By assigning a [`displayName`](https://legacy.reactjs.org/docs/react-component.html#displayname), they are displayed with correct names:
Assigning `displayName` is necessary since merely this...
```diff
const AppForm = useMemo(() => {
-      return (({ children }) => {
+      const AppForm = (({ children }) => {
```
...would display as `<AppForm2>` instead since it is renamed when compiled:
```js
const AppForm = useMemo(() => {
const AppForm2 = ({ children }) => {
return /* @__PURE__ */ jsx(formContext.Provider, { value: …
```
=> feat(react-form): add display name to components

docs/framework/solid/guides/form-composition.md
I missed a few references in solid's form composition guide.
This fixes those.
=> docs(solid-form): update examples from react to solid.

packages/form-core/src/utils.ts, packages/form-core/tests/utils.spec.ts
Closes #1617
A field name like '01234' was being incorrectly treated as the number 1234 inside the `makePathArray` utility. This caused the form to set values using the wrong key, leading to data mismatches and stale fields.
The logic in makePathArray has been updated to be more precise. It now checks if converting a numeric string to a number would change its value (e.g., by stripping leading zeros). If it would, the original string is kept. This resolves the bug without affecting how standard array indices are parsed.
=> fix(form-core): preserve leading zeros in numeric string field names

packages/react-form/src/createFormHook.tsx
This PR moves the field and form context to module scope and exports them through the context creation. It avoids Vite's HMR creating new context and breaking the connection by accident.
This will need testing to confirm that it fixed the problems. Until that is confirmed, it's marked as draft.
=> fix(react-form): retain field and form context during Hot Module Replacement

docs/framework/react/guides/form-composition.md
The HTML `label` tag should not contain a `div`, so this change replaces the `div` with a `span`
Source:
https://caninclude.onrender.com/caninclude?child=div&parent=label
=> docs(react-form): fix invalid HTML markup in Form Composition

packages/react-form/src/createFormHook.tsx, packages/react-form/src/index.ts, packages/solid-form/src/index.tsx
Close #1646 
This type export is required so that libraries with declaration file generation can create explicit types instead of non-portable references.
It's finnicky to trigger the warning or error, so feedback will be needed from users in the linked issue before this is safe to merge.
=> fix(react-form): export returned types from `createFormHook`

docs/config.json, docs/framework/lit/guides/validation.md
This pull request adds a new entry to the `docs/config.json` file to include a guide on validation in the documentation.
* [`docs/config.json`](diffhunk://#diff-6d9273c3bfa0b82e1f9b00029de2eff3cc18f3f06850bf3301b3586b60f463aaR237-R240): Added a new navigation item labeled "Validation" with a link to `framework/lit/guides/validation`.
=> docs: migrate validation docs to Lit

packages/form-core/src/formOptions.ts, packages/form-core/tests/FormApi.test-d.ts
- Add TFormData generic parameter to formOptions function
- Add test to verify listener type preservation with formOptions
- Current implementation has intentional type issues for investigation
=> fix(form-core): infer `formOptions` parameter's type correctly

docs/framework/react/guides/custom-errors.md
- removed a stray semicolon (;) that appeared after a JSX comment
- replaced comment with a regular line comment (// ...) for better readability
i think that semicolon was unnecessary and could confuse readers when copying or reading the example. 🤔
=> docs(react-form): fix incorrect error display in example

packages/form-core/src/FieldApi.ts, packages/form-core/src/FormApi.ts, packages/form-core/src/types.ts, packages/form-core/src/utils.ts, packages/form-core/tests/utils.spec.ts
Also adds two meta properties, `dontValidate` and `dontRunListeners`. Should help in case someone wants extreme control, but it's more for our sake.
=> fix(form-core): Trigger listeners and validation on `setFieldValue`

packages/form-core/src/utils.ts, packages/form-core/tests/utils.spec.ts
Fixes issue where `isDefaultValue` was not updating correctly when changing date fields.
The `evaluate` function was treating Date objects as regular objects, causing incorrect equality comparisons for date values.
- Added specific Date object comparison using `getTime()` method
- Added comprehensive tests for Date object comparison scenarios
Closes #1712
=> fix(form-core): prevent stale reactivity when using Date objects

scripts/tsconfig.json, tsconfig.json
This project previously didn't work without moduleResolution node in the root-level tsconfig. I can't remember why (maybe TS versions?), but I think it will work now.
=> chore(typescript): use moduleResolution bundler

docs/philosophy.md
This pull request makes a small documentation fix by correcting a typo in the `docs/philosophy.md` file. The word "inference" was changed to "infer" for grammatical accuracy.Corrected a typo in the documentation regarding generics.
=> Fix typo in generics explanation
