- README.md
https://npmjs.com/package/react-form was missing the "e" in package.
> Fixed broken npm link

- src/formInputs/checkbox.js
- src/formInputs/radio.js
- src/formInputs/select.js
- src/formInputs/text.js
- src/formInputs/textarea.js
Such that I could use `showErrors={false}` to hide each error and use `FormError` instead.
For example, One error message for radiogroup instead of three error messages:
**Before**:
**After**:
**Code changes**:
```diff
diff --git a/example/src/screens/simple.js b/example/src/screens/simple.js
index 8030552..8e43fc9 100644
--- a/example/src/screens/simple.js
+++ b/example/src/screens/simple.js
@@ -15,7 +15,7 @@ const MyForm = Form({
// Validating your form is super easy, just use the `validate` life-cycle method
validate: values => {
-    const { name, hobby, status, friends, address } = values
+    const { name, hobby, status, friends, address, notificationType } = values
return {
name: !name ? 'A name is required' : undefined,
hobby: (hobby && hobby.length < 5) ? 'Your hobby must be at …
```
> Allow pre-packaged form inputs to pass specific props to FormInput component

- README.md
- src/formInputs/checkbox.js
- src/formInputs/radio.js
- src/formInputs/select.js
- src/formInputs/text.js
- src/formInputs/textarea.js
I wanted to be able to modify `noTouch` values for each input so that validation only runs on blur. Also added documentation about `noTouch` on README.
> Allow noTouch to be customizable / Document

- .storybook/config.js
- .storybook/head.html
- package.json
- stories/Demo.js
- stories/DemoForm.js
- stories/ReactFormWrapper.js
- stories/Simple.js
- stories/SimpleCheckbox.js
- stories/SimpleText.js
> add storybook

- package.json
https://github.com/tannerlinsley/react-form/issues/38
> Fixed dependencies

- README.md
Was not clear to me from the docs what the "form state" object that `loadState()` was expected to return. Needed to read the source to understand. This should make it more evident to readers what the form state object is.
> Improve documentation of form state object

- README.md
Fixes a minor grammar issue in readme.
> minor grammar update

- src/components/ReduxForm.js
> Pass submit event to onSubmit

- src/components/DeprecatedFormField.js
- src/components/FormField.js
I found a spelling mistake when reading the source code. So I created this merge request.
Please check. Thank you in advance.
> Change Depricated to Deprecated

- src/components/form-fields/Radio.js
- src/components/styled-form-fields/Radio.js
Little change to propTypes to avoid unnecessary warning when using bool value on Radio input :)
> chore: Radio input does not have warning with bool value

- docs/api.md
Feel free to update or request some wording/clarity fixes!
> Add getInputProps to Field instance docs

- .babelrc
> feat: do not transpile async

- docs/api.md
debugForm option was under Form Instance but it only works as an option
> debugForm in wrong section

- src/hooks/useAsyncDebounce.js
Should fix https://github.com/tannerlinsley/react-form/issues/355.
> fix: correctly handle debounce error

- examples/react/simple/.eslintrc
- examples/react/simple/.eslintrc.cjs
- examples/react/simple/src/index.tsx
- examples/react/simple/tsconfig.json
This PR fixes ESLint for the example React project to make actual errors stick out properly
> chore: fix eslint for example project

- docs/comparison.md
> Add github starts for other libraries in comparison page

- docs/guides/basic-concepts.md
- docs/guides/important-defaults.md
- docs/installation.md
- docs/overview.md
- docs/reference/fieldApi.md
- docs/reference/formApi.md
- examples/react/simple/package.json
- examples/react/simple/src/index.tsx
- pnpm-lock.yaml
This PR adds some initial docs improvements to make them match the codebase's actual functionality.
Additionally, it includes a CTA for pages that are not up-to-date with the most recent API changes to reach out in our Discord.
> docs: improve docs, add disclaimer where docs are outdated

- README.md
Fixes the header image in README and removes a badge that doesn't load anymore
> docs: fix header image in README

- README.md
This fixes a link I missed when I made #413
> docs: fix bundlephobia link

- docs/comparison.md
> docs: add bundle size and supported frameworks

- packages/react-form/src/tests/useField.test.tsx
- packages/react-form/src/tests/useForm.test.tsx
- packages/react-form/src/tests/utils.ts
This PR creates a new file for `useField` related tests and adds the `onChange` validation tests along with a small test for the `defaultValue` there
> test(react-form): add on change validation tests

- docs/framework/react/quick-start.md
I think this is correct form.Form didn't work for me
> Update quick-start.md to .Provider

- .github/FUNDING.yml
With permission from Tanner, I'm adding myself to the funding array, replacing a value set for Query's repo originally.
> chore: add crutchcorn to gh funding

- examples/react/valibot/src/index.tsx
- examples/solid/valibot/src/index.tsx
- examples/vue/valibot/src/App.vue
Sorry, I added a bug in #518 and fixed it with this PR
> fix: async Valibot string validation

- .github/workflows/ci.yml
- .github/workflows/pr.yml
I'm hoping this will "just work", i.e. that the secret has already been configured.
> chore: Enable Nx distributed caching

- examples/vue/simple/package.json
- examples/vue/valibot/package.json
- examples/vue/yup/package.json
- examples/vue/zod/package.json
- packages/vue-form/package.json
- pnpm-lock.yaml
Changelog: https://github.com/vitejs/vite-plugin-vue/blob/main/packages/plugin-vue/CHANGELOG.md
> chore: Update @vitejs/plugin-vue to v5

- docs/config.json
- docs/framework/react/guides/react-native.md
> docs: add react-native usage guide

- docs/config.json
- docs/framework/react/guides/next-js.md
- docs/framework/react/guides/ssr.md
- Usage of `NextJs` with App router and using server actions
- @crutchcorn  as discussed on discord here is the usage of `form` with server actions, let me know if updates are needed
Thank you!
> docs(next-usage): usage of serveractions with next

- docs/guides/validation.md
Closes #578 
I hopefully found all of them.
> Fix validators syntax

- examples/react/ui-libraries/package.json
- package.json
- packages/form-core/package.json
- packages/react-form/package.json
- packages/solid-form/package.json
- packages/vue-form/package.json
- pnpm-lock.yaml
- Use latest tanstack/config and tanstack/store
- Update Nx, vite, vitest
> chore: Update TanStack and workspace dependencies

- .github/workflows/pr.yml
- .gitignore
- .nx/workflows/dynamic-changesets.yaml
- nx.json
See here: https://github.com/TanStack/query/pull/6863
> ci: Add Nx Agents

- .eslintrc.cjs
- .gitignore
- knip.json
- nx.json
- package.json
- packages/form-core/src/types.ts
- packages/react-form/package.json
- packages/react-form/src/tests/createFormFactory.test.tsx
- packages/react-form/src/tests/useField.test.tsx
- packages/react-form/src/tests/useForm.test.tsx
- packages/solid-form/src/tests/createField.test.tsx
- packages/solid-form/src/tests/createForm.test.tsx
- packages/solid-form/src/tests/createFormFactory.test.tsx
- packages/vue-form/src/tests/useForm.test.tsx
- pnpm-lock.yaml
- Enabled knip and fixed errors
- Updated gitignore
- I attempted to enable `@typescript-eslint/method-signature-style`, but this led to type issues with the adapters
> chore: Add workspace config from Query

- docs/config.json
This should fix the homepage after I broke it in #641
> chore: fix homepage from loading

- docs/framework/angular/guides/arrays.md
- examples/angular/array/src/app/app.component.ts
As highlighted here: https://twitter.com/ninan_phillip/status/1771659578276458609
This PR fixes issues documented in our array usage of Angular TanStack Form
> docs: document a fix to the issues with TypeScript types in ng arrays

- docs/framework/react/guides/basic-concepts.md
I think the author meant it the other way around.
> Update RHF isDirty note

- packages/form-core/src/FieldApi.ts
- packages/form-core/src/FormApi.ts
- packages/form-core/src/utils.ts
- packages/react-form/src/tests/useField.test.tsx
> fix: onSubmit should forcably set onChange and onBlur validation to execute immediately

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- package.json
- packages/react-form/package.json
- packages/solid-form/package.json
- packages/vue-form/package.json
- pnpm-lock.yaml
This PR upgrades to PNPM 9 and fixes some issues with Windows building
> chore: migrate to PNPM version 9, fix build on Windows

- .npmrc
- pnpm-lock.yaml
- Default setting changed to false in pnpm v9
- Fixes local development of examples
> chore: Enable link-workspace-packages

- docs/framework/react/guides/basic-concepts.md
I updated this part a bit as we said on Discord, does the note look ok?
> docs: mention useStore in favor of useField

- docs/framework/react/guides/arrays.md
> docs: add array mode on react guide

- docs/framework/react/guides/ssr.md
Requested on #710 (but doesn't close that issue).
I didn't run the docs locally since it was a small change. If I should, comment that, and I will look into it.
> docs: add note about backend leak on ssr example

- nx.json
https://twitter.com/crutchcorn/status/1803315755964047755
> chore: remove nx cloud temporarily

- package.json
- packages/angular-form/ng-package.json
- packages/angular-form/package.json
- packages/form-core/package.json
- packages/lit-form/package.json
- packages/react-form/package.json
- packages/solid-form/package.json
- packages/valibot-form-adapter/package.json
- packages/vue-form/package.json
- packages/yup-form-adapter/package.json
- packages/zod-form-adapter/package.json
- pnpm-lock.yaml
- Updated to latest `@tanstack/angular-store` build (https://github.com/TanStack/store/pull/62)
- Moved angular-form build to `./dist` for consistency with other adapters
- Added correct repository field to packages
> chore: Update TanStack Store dependencies

- packages/react-form/src/useField.tsx
> fix: arrays with null default values should no longer throw

- packages/angular-form/package.json
- packages/form-core/package.json
- packages/lit-form/package.json
- packages/solid-form/package.json
- packages/valibot-form-adapter/package.json
- packages/vue-form/package.json
- packages/yup-form-adapter/package.json
- packages/zod-form-adapter/package.json
Explainer: https://github.com/TanStack/form/issues/787#issuecomment-2194765568
> fix: republish packages with correct resolutions

- examples/react/array/src/index.tsx
- examples/react/next-server-actions/next.config.cjs
- examples/react/query-integration/src/index.tsx
- examples/react/simple/src/index.tsx
- examples/react/ui-libraries/src/index.tsx
- examples/react/valibot/src/index.tsx
- examples/react/yup/src/index.tsx
- examples/react/zod/src/index.tsx
I also had a quick run on the examples one by one and it seems they are working fine. It's time to enable StrictMode! 🙌
> docs: enable strict mode in react examples

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- .nx/workflows/dynamic-changesets.yaml
- eslint.config.js
- package.json
- pnpm-lock.yaml
- Use shared setup action from tanstack/config
- Run start-ci-run immediately after checkout
- Reduce dynamic-changesets
> ci: Optimise Nx workflow

- docs/framework/react/guides/ssr.md
- update `initialFormState` path in SSR/Next.js.
- format existing import to one line.
https://github.com/TanStack/form/issues/802
> docs: update SSR/Next.js `initialFormState` import

- .github/workflows/preview.yml
- package.json
- packages/angular-form/package.json
- packages/form-core/package.json
- packages/lit-form/package.json
- packages/react-form/package.json
- packages/solid-form/package.json
- packages/valibot-form-adapter/package.json
- packages/vue-form/package.json
- packages/yup-form-adapter/package.json
- packages/zod-form-adapter/package.json
- pnpm-lock.yaml
Powered by https://github.com/stackblitz-labs/pkg.pr.new
> ci: Add preview workflow

- docs/config.json
- docs/framework/react/guides/ssr.md
- packages/react-form/README.md
- packages/solid-form/README.md
This PR adds docs for TanStack Form <-> Start
Closes: #753
> docs: add documentation for TanStack Start

- docs/config.json
- docs/framework/solid/guides/arrays.md
- docs/framework/solid/guides/async-initial-values.md
- docs/framework/solid/guides/basic-concepts.md
- docs/framework/solid/guides/linked-fields.md
- docs/framework/solid/guides/validation.md
Updated Solid docs by adding the following guides:
- Basic Concepts
- Form Validation
- Async Initial Values
- Linked Fields
#748
> docs: update solid docs

- examples/react/array/tsconfig.json
- examples/react/query-integration/tsconfig.json
- examples/react/simple/tsconfig.json
- examples/react/valibot/tsconfig.json
- examples/react/yup/tsconfig.json
- examples/react/zod/tsconfig.json
Based on more recent create-vite template
> docs(examples): Update tsconfig.json for React examples

- .github/renovate.json
- examples/angular/simple/src/app/app.component.ts
- examples/angular/valibot/src/app/app.component.ts
- examples/angular/yup/src/app/app.component.ts
- examples/angular/zod/src/app/app.component.ts
- knip.json
- nx.json
- package.json
- packages/angular-form/tests/test.component.spec.ts
- packages/form-core/src/FieldApi.ts
- packages/form-core/src/FormApi.ts
- pnpm-lock.yaml
- Enable automerge
- Enable lockfile maintenance
- Don't run prettier on Nx (covered by autofix.ci)
> ci(renovate): update renovate config

- examples/react/next-server-actions/package.json
- examples/react/next-server-actions/src/app/client-component.tsx
- pnpm-lock.yaml
> fix(examples): fix next server actions example

- docs/reference/classes/fieldapi.md
- docs/reference/classes/formapi.md
- packages/form-core/src/FieldApi.ts
- packages/form-core/src/FormApi.ts
This PR fixed issues that arose with merging #962.
> chore: fix timeout issues

- docs/reference/classes/formapi.md
- packages/form-core/src/FieldApi.ts
- packages/form-core/src/FormApi.ts
- packages/form-core/src/utils.ts
- packages/form-core/tests/FormApi.spec.ts
> fix: spread field errors on form onMount validator

- docs/reference/classes/fieldapi.md
- docs/reference/classes/formapi.md
- packages/form-core/src/FieldApi.ts
- packages/form-core/src/FormApi.ts
- packages/form-core/tests/FormApi.spec.ts
> fix(form-core): skip form validation for each single field on form submit

- packages/form-core/src/utils.ts
> fix: RN on Android no longer needs a replaceAll polyfill

- docs/reference/classes/fieldapi.md
- docs/reference/interfaces/fieldapioptions.md
- docs/reference/interfaces/fieldlisteners.md
- docs/reference/interfaces/fieldoptions.md
- docs/reference/interfaces/fieldvalidators.md
- docs/reference/type-aliases/anyfieldapi.md
- docs/reference/type-aliases/anyfieldmeta.md
- docs/reference/type-aliases/anyfieldmetabase.md
- docs/reference/type-aliases/anyfieldmetaderived.md
- docs/reference/type-aliases/fieldmeta.md
- docs/reference/type-aliases/fieldmetabase.md
- docs/reference/type-aliases/fieldmetaderived.md
- docs/reference/type-aliases/fieldstate.md
- docs/reference/type-aliases/unwrapfieldasyncvalidateorfn.md
- docs/reference/type-aliases/unwrapfieldvalidateorfn.md
- packages/form-core/src/FieldApi.ts
- packages/form-core/tests/FieldApi.test-d.ts
- packages/form-core/tests/standardSchemaValidator.test-d.ts
> fix: subfields should now return the correct validation errors in TS

- docs/reference/classes/formapi.md
- docs/reference/type-aliases/anyformapi.md
- docs/reference/type-aliases/anyformstate.md
- docs/reference/type-aliases/baseformstate.md
- docs/reference/type-aliases/derivedformstate.md
- docs/reference/type-aliases/formstate.md
- packages/form-core/src/FormApi.ts
Fixes: #1145, #1135
Sorry about this all, I didn't consider this edgecase originally
> fix: transform changes at runtime should now work

- docs/config.json
- docs/framework/react/guides/submission-handling.md
From issue #1183 and PR #1167, this PR introduces documentation for submission handling and the onSubmitMeta API.
> feat(docs): onSubmitMeta and submission handling

- docs/framework/react/guides/form-composition.md
- examples/react/large-form/src/App.tsx
- examples/react/large-form/src/components/text-fields.tsx
- examples/react/large-form/src/hooks/form-context.tsx
- examples/react/large-form/src/hooks/form.tsx
This helps solve problems for huge UI libraries
> docs: include example of React.lazy for tree-shaking

- docs/framework/react/quick-start.md
Per a conversation I had with @phryneas, this "get started" guide for React might serve as a better jumping off point for users.
> docs: improve get started guide for React to be more representative

- docs/config.json
Closes #1212 
Happy to move the menu item and relabel if ya need!
> docs: add large form example to side menu

- CONTRIBUTING.md
Takes more recent changes to query (mainly code blocks)
> chore: sync CONTRIBUTING.md between projects

- docs/framework/react/guides/ssr.md
Theo t3.gg noted that the imports was missing in a video on tanstack form so here's a tiny PR
> docs(react): missing useStore imports

- docs/framework/react/guides/reactivity.md
> docs: fix typo in reactivity.md

- docs/reference/classes/formapi.md
- docs/reference/type-aliases/deepkeys.md
- docs/reference/type-aliases/deeprecord.md
- docs/reference/type-aliases/deepvalue.md
- packages/form-core/src/util-types.ts
- packages/form-core/tests/util-types.test-d.ts
> fix: handle discriminated unions in types

- packages/lit-form/src/index.ts
> fix(lit-form): add explicit export path to lit-form index.js

- docs/framework/react/guides/ssr.md
I think that's more correct nomenclature
> docs(react): fix server action typo

- examples/react/next-server-actions/package.json
- examples/react/remix/package.json
- examples/react/tanstack-start/package.json
- packages/angular-form/package.json
- packages/form-core/package.json
- packages/react-form/package.json
- packages/solid-form/package.json
- packages/svelte-form/package.json
- packages/vue-form/package.json
- pnpm-lock.yaml
This PR upgrades TanStack Store to hopefully help with stability around Dates and performance improvements for SolidJS
> Upgrade TanStack Store

- docs/framework/angular/guides/basic-concepts.md
- docs/framework/react/guides/basic-concepts.md
- docs/framework/solid/guides/basic-concepts.md
- docs/framework/svelte/guides/basic-concepts.md
- docs/framework/vue/guides/basic-concepts.md
Added yup to the list of libraries supporting Standard Schema, as well as the versions required to use them.
> docs: Update Standard Schema library list

- docs/config.json
- docs/framework/react/guides/focus-management.md
This PR adds docs for focusing first field that has an error for React.
I originally did not document this because of a misunderstanding on my end about the implications of A11Y around this pattern. Apologies
> docs: add focus management docs for React

- package.json
- pnpm-lock.yaml
Not that it really matters, but this moves the new changesets deps alongside the other workspace-wide deps.
> chore(deps): Move changesets to devdeps

- .github/workflows/pr.yml
See here: https://github.com/danielroe/provenance-action
> ci: add `danielroe/provenance-action`
